name = "QuantumDynamics"
uuid = "5a40c529-53c2-4483-a223-e00c1cee8134"
authors = ["Amartya Bose <amartya.bose@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
DifferentialEquations = "7"
ITensors = "0.3"
Kronecker = "0.5"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
